import type { ScrapbookCard } from './types';

export const CURATED_CARDS: ScrapbookCard[] = [
  {
    id: 'gamers',
    title: 'Best Gifts for Gamers',
    picksCount: 12,
    badgeBg: 'bg-[#81b29a]',
    badgeText: 'text-white',
    image: 'https://m.media-amazon.com/images/I/817lZy54A9L._SL1500_.jpg',
    description: 'Essential gear and rare collectibles curated for every setup.',
    category: 'recipients',
    tags: ['Gamer', 'Tech', 'Desk Accessories'],
    items: [
      {
        id: 'g1',
        name: 'Ergonomic Gaming Chair',
        price: '8k',
        description: 'Premium PU Leather, Adjustable Neck & Lumbar Pillow, 180 Degree Recline with Black Metal Base with 3 Years Warranty.',
        link: 'https://link.amazon/B0aF67BKN',
      },
      {
        id: 'g2',
        name: 'Wireless Mechanical Keyboard ',
        price: '6k',
        description: 'Hot Swappable | Pre-lubed Linear Switches | RGB Backlit | 2.4GHz/Type-C/Bluetooth Gaming Keyboard',
        link: 'https://link.amazon/B0d5qG0XF',
      },
      {
        id: 'g3',
        name: 'Wireless Gaming Controller',
        price: '1.5k',
        description: 'EvoFox One S V2 Universal 3-Mode Wireless Gaming Controller, HallSense™ Precision Joysticks, Bluetooth 5.0, 2.4GHz, Fast Type-C Charging for PC, Mobile, Android TV - White',
        link: 'https://link.amazon/B0cG1oeIV',
      },
      {
        id: 'g4',
        name: 'Wired Headset',
        price: '4.4k',
        description: 'Razer BlackShark V2 X - White | Multi-Platform Wired Esports On Ear Headset - RZ04-03240700-R3M1.',
        link: 'https://link.amazon/B02GJf9hu',
      },
    ],
  },
  {
    id: 'book-lovers',
    title: 'Gifts for the Well-Read',
    picksCount: 8,
    badgeBg: 'bg-[#d4a373]',
    badgeText: 'text-white',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDH6NKlHouPKY6gJfcU-5D8mfMr7HBhEHw1eFTDbdRmq3qRFfNI_XacX8VI6icR2zcQn1DBJizKIlGw6hUVu0AQJvVwFRRIDzngT2W-sFDG_m7QONBH_PVog-qpqw0U65fgybmimzYmsemMRJqCq57f9jpNQkZTN4xKDtXqAUa_Lixnfw7_9EnOiY409XEcX1dbBgdN3-vFkl0rDSlfj2k5yE-Jbe6cWTVbTmA8Yyzzby82ImhQiRCrYYwbaiIy1XikYZ3QJoilAPae',
    description: 'Accessories that turn any corner into a sanctuary.',
    category: 'occasions',
    tags: ['Cozy', 'Home', 'Relaxing'],
    items: [
      {
        id: 'b1',
        name: 'Amber Eye-Care Rechargeable Reading Light',
        price: '$18',
        description: 'Blocks 99.9% of blue light, emitting a gentle sunset-like glow to help you read comfortably without disrupting sleep.',
        link: '#',
      },
      {
        id: 'b2',
        name: 'Solid Brass Arch Bookends (Pair)',
        price: '$48',
        description: 'Heavyweight, brushed-finish minimalist arches that hold heavy hardcovers while reflecting a beautiful warm light.',
        link: '#',
      },
      {
        id: 'b3',
        name: '"Old Library" Hand-Poured Soy Candle',
        price: '$28',
        description: 'Notes of rich mahogany wood, paper dust, worn leather covers, and a soft base of amber vanilla.',
        link: '#',
      },
      {
        id: 'b4',
        name: 'Handcrafted Embossed Leather Journal',
        price: '$35',
        description: 'Features 200 pages of recycled deckled-edge cotton paper bound in authentic full-grain distress leather with strap.',
        link: '#',
      },
    ],
  },
  {
    id: 'moms',
    title: 'Thoughtful Gifts for Mom',
    picksCount: 15,
    badgeBg: 'bg-[#e07a5f]',
    badgeText: 'text-white',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBZYZvOp4iE90e0X4RPS6Fi-pFuUppK-ivs9QvvIAbvC5r_kMSn0Lj6cFrfaeLBD-ThF3skAiVxT0I6aC9PffusnKgARz2EhupFVBWZ6jU0dav6uQ-HB6EBr5Qi_vqAI6Cvk1URuJT8MhcM_5He3LmT8V-CcWsB37h00llzux2N_lzpeYXJjcvtsDDz31MZFCAlQ3gmwOHTCeZ18rZzGdvH9eeyCWR6USv1cDRSGaK4RGpbur0BWnMMjEvlCLiAd7csC-RcKCKVoFNj',
    description: 'Curated treasures that speak louder than words.',
    category: 'recipients',
    tags: ['Mom', 'Luxury', 'Personalized'],
    items: [
      {
        id: 'm1',
        name: 'Pressed Wildflower Hanging Glass Frame',
        price: '$40',
        description: 'Real dried buttercups and fern fronds pressed between solid glass panes within a polished brass hanging chain frame.',
        link: '#',
      },
      {
        id: 'm2',
        name: 'Mulberry Pure Silk Sleep Mask',
        price: '$29',
        description: '100% natural mulberry silk front, back, and filling, designed to protect delicate facial skin and prevent creases.',
        link: '#',
      },
      {
        id: 'm3',
        name: 'Glazed Oatmeal Ceramic Matcha Set',
        price: '$55',
        description: 'Includes a spout bowl, bamboo whisk (chasen), and ceramic whisk holder, hand-painted with speckled oat-colored glaze.',
        link: '#',
      },
      {
        id: 'm4',
        name: 'Dainty Raw Birthstone Necklace',
        price: '$75',
        description: 'An elegant, delicate 14k gold-filled chain adorned with three genuine, raw, rough-cut birthstones of your choice.',
        link: '#',
      },
    ],
  },
  {
    id: 'eco-friendly',
    title: 'Eco-Friendly Finds',
    picksCount: 10,
    badgeBg: 'bg-[#8c7b70]',
    badgeText: 'text-white',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyAWxer2Cl25R1ypC6uwpZpr6l7OvBE4gJuAq55TACUGqxslA_lGbGXKTcND9BQEVJRUEs9Zr2SymqAEAWOpULjqRxh8A-gYLtGlVLpIkr0eJFY0GC3slkc9uqBvUQbKJkYOfZyaDQW-cdY4QBovyzwmnLi6Wre4SZJKyf7yz3B9Gwy-Wv5_BrJKcwYw6RxVOtYi3LleS0xJ_su7rjhF-RSOb8GeGIjQrETlSeQeHSXG18hHvFSqbIhjw6BjpC2dq30HPzURPbJx_j',
    description: 'Sustainable choices that never compromise on beauty.',
    category: 'sustainability',
    tags: ['Eco', 'Sustainable', 'Outdoor'],
    items: [
      {
        id: 'e1',
        name: 'Upcycled Coffee Ground Coffee Mug',
        price: '$24',
        description: 'An insulating double-walled travel mug pressed from real recycled coffee husks and grounds, smelling faintly of mocha.',
        link: '#',
      },
      {
        id: 'e2',
        name: 'Beeswax Organic Cotton Food Wraps (Pack of 3)',
        price: '$15',
        description: 'Clings tightly to bowls and ingredients with the heat of your hands, replacing single-use plastics with beautiful botanic prints.',
        link: '#',
      },
      {
        id: 'e3',
        name: 'Solar-Powered Collapsible Lantern',
        price: '$45',
        description: 'An inflatable, completely waterproof LED lantern that floats and doubles as a solar-powered backup USB charger.',
        link: '#',
      },
      {
        id: 'e4',
        name: 'Unbleached Organic Cotton Waffle Robe',
        price: '$85',
        description: 'Super-soft and absorbent waffle knit, dyed with natural avocado seeds and walnut shells for a soft, warm earthy tone.',
        link: '#',
      },
    ],
  },
  {
    id: 'chef',
    title: 'The Culinary Collector',
    picksCount: 22,
    badgeBg: 'bg-[#f2cc8f]',
    badgeText: 'text-[#5d4037]',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcEwUuuB9B7HWIy502aZgAEWv_M9CUrhFf59fnPtxekGSYyH4lVuVlA9fSXV-EynvjaDf0an4SYdx93i3x61_ElGMA2rTLanw7SFVFevHke-ihUZgfZ2lJXDt1aUNUInHKfD31b3P79wDcK43ajdZhF1THbPiXDEW8xNNsb2SvU5seHi4zQaYSxP5jtXV3H4KXnRmIr0lBhbOk9qi5IySS4eMbTKtGmeavgSqAzlLcNhh0ne2Hbi5GTK0GzFktz-_Rz9eTXbw6MYnq',
    description: 'Artisan tools and rare ingredients for the one who lives to create in the kitchen.',
    category: 'recent',
    tags: ['Chef', 'Kitchen', 'Gourmet'],
    items: [
      {
        id: 'c1',
        name: 'Hand-Forged 67-Layer Damascus Paring Knife',
        price: '$120',
        description: 'Features an ultra-hard VG-10 steel core sandwiched between beautiful swirling ripples and a natural olive wood ergonomic handle.',
        link: '#',
      },
      {
        id: 'c2',
        name: 'Speckled Stoneware Fermentation Crock',
        price: '$65',
        description: '1-gallon pickling jar equipped with dual clay weights and an air-tight water channel lid for fermenting premium kimchi or kraut.',
        link: '#',
      },
      {
        id: 'c3',
        name: 'Aged Truffle Infused Olive Oil in Clay Cruet',
        price: '$38',
        description: 'Cold-pressed extra virgin olive oil infused with real shavings of white Umbrian truffles, packaged in a reusable hand-thrown clay bottle.',
        link: '#',
      },
      {
        id: 'c4',
        name: 'Raw Speckled Granite Mortar & Pestle',
        price: '$50',
        description: 'Heavy 8-pound rough-textured granite bowl that extracts full flavor and essential oils from peppercorns, herbs, and garlic easily.',
        link: '#',
      },
    ],
  },
  {
    id: 'coffee-enthusiast',
    title: 'The Daily Ritual',
    picksCount: 14,
    badgeBg: 'bg-[#1A1A1A]',
    badgeText: 'text-white',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop',
    description: 'Slow-brew accessories and micro-roaster select beans for elevated mornings.',
    category: 'occasions',
    tags: ['Coffee', 'Morning', 'Brewing'],
    items: [
      {
        id: 'c_e1',
        name: 'Hand-Blown Borosilicate Glass Dripper',
        price: '$42',
        description: 'A minimalist double-walled glass dripper that maintains water temperature for a perfect extraction.',
        link: '#',
      },
      {
        id: 'c_e2',
        name: 'Precision Gooseneck Kettle',
        price: '$95',
        description: 'Counterbalanced handle and thin spout for steady flow rate control, featuring an integrated dial thermometer.',
        link: '#',
      },
      {
        id: 'c_e3',
        name: 'Japanese Hinoki Wood Coffee Spoon',
        price: '$22',
        description: 'Handcrafted from fragrant Japanese cypress wood, bringing a forest aroma to your morning routine.',
        link: '#',
      },
      {
        id: 'c_e4',
        name: 'Double-Wall Ceramic Tumbler (Pair)',
        price: '$38',
        description: 'Sleek, handleless cups with a rough stoneware exterior and a smooth matte interior.',
        link: '#',
      },
    ],
  },
  {
    id: 'modern-nomad',
    title: 'The Modern Nomad',
    picksCount: 11,
    badgeBg: 'bg-[#E2D1C3]',
    badgeText: 'text-[#1A1A1A]',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=600&auto=format&fit=crop',
    description: 'Ultralight carrying essentials and compact utilities for the global wanderer.',
    category: 'recipients',
    tags: ['Travel', 'Minimalist', 'Gear'],
    items: [
      {
        id: 'm_n1',
        name: 'Tyvek Waterproof Compression Organizer',
        price: '$30',
        description: 'Extremely durable and featherlight packing cubes that compress your clothing to half its volume.',
        link: '#',
      },
      {
        id: 'm_n2',
        name: 'Minimalist Solid Brass Pen',
        price: '$50',
        description: 'A weighted pocket-sized pen that accepts standard refills and develops a unique patina over time.',
        link: '#',
      },
      {
        id: 'm_n3',
        name: 'Universal Leather Travel Tech Cord Wrap',
        price: '$45',
        description: 'Handcrafted vegetable-tanned leather organizer with modular snaps to secure all your charging cables.',
        link: '#',
      },
      {
        id: 'm_n4',
        name: 'Noise-Isolating Memory Foam Earplugs',
        price: '$20',
        description: 'Reusable, high-fidelity acoustic filters in an ultra-compact brass carrying cylinder.',
        link: '#',
      },
    ],
  },
  {
    id: 'backyard-host',
    title: 'The Backyard Host',
    picksCount: 16,
    badgeBg: 'bg-[#FAF9F6]',
    badgeText: 'text-[#1A1A1A]',
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=600&auto=format&fit=crop',
    description: 'Warm ambient lighting and functional serving pieces designed for golden hour.',
    category: 'occasions',
    tags: ['Hosting', 'Outdoor', 'Cozy'],
    items: [
      {
        id: 'b_h1',
        name: 'Handwoven Rattan Drink Pitcher',
        price: '$48',
        description: 'A classic heat-resistant glass pitcher encased in a beautifully structured natural cane holder.',
        link: '#',
      },
      {
        id: 'b_h2',
        name: 'Hammered Copper Wine Chiller',
        price: '$55',
        description: 'Double-walled insulation that keeps bottles cold for hours without ice, finished with a raw hammered texture.',
        link: '#',
      },
      {
        id: 'b_h3',
        name: 'Scented Citronella & Cedar Outdoor Candle',
        price: '$32',
        description: 'Poured into a rustic terracotta bowl to keep mosquitoes away with clean essential oils.',
        link: '#',
      },
      {
        id: 'b_h4',
        name: 'French Linen Oversized Napkins (Set of 4)',
        price: '$36',
        description: 'Soft pre-washed organic linen with delicate frayed edges in a warm toasted sesame hue.',
        link: '#',
      },
    ],
  },
  {
    id: 'pet-lovers',
    title: 'Aesthetic Pet Companions',
    picksCount: 9,
    badgeBg: 'bg-[#1A1A1A]',
    badgeText: 'text-white',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=600&auto=format&fit=crop',
    description: 'Beautifully designed pet objects that complement modern home interiors.',
    category: 'recipients',
    tags: ['Pets', 'Home', 'Design'],
    items: [
      {
        id: 'p_l1',
        name: 'Hand-Carved Stone Pet Food Bowl',
        price: '$42',
        description: 'Heavy solid soapstone bowl that won\'t slide on hardwood floors, keeping water naturally cool.',
        link: '#',
      },
      {
        id: 'p_l2',
        name: 'Organic Wool Felt Cat Cave',
        price: '$68',
        description: 'Handmade by artisans from 100% pure organic wool, providing a cozy and private sanctuary.',
        link: '#',
      },
      {
        id: 'p_l3',
        name: 'Natural Hemp Rope Tug Toy',
        price: '$18',
        description: 'Unbleached hemp fibers that naturally clean teeth during play, without artificial dyes.',
        link: '#',
      },
      {
        id: 'p_l4',
        name: 'Minimalist Leather Brass Collar',
        price: '$35',
        description: 'Full-grain bridle leather equipped with solid brass hardware and an elegant silent tag ring.',
        link: '#',
      },
    ],
  },
  {
    id: 'desk-curator',
    title: 'The Desk Curator',
    picksCount: 18,
    badgeBg: 'bg-[#E2D1C3]',
    badgeText: 'text-[#1A1A1A]',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&auto=format&fit=crop',
    description: 'Architectural desk accessories to organize thoughts and tools beautifully.',
    category: 'sustainability',
    tags: ['Workspace', 'Design', 'Minimal'],
    items: [
      {
        id: 'd_c1',
        name: 'Concrete Tray & Phone Dock',
        price: '$38',
        description: 'Cast in smooth architectural concrete with cork pads to protect your devices and desktop surface.',
        link: '#',
      },
      {
        id: 'd_c2',
        name: 'Brushed Aluminum Desktop Ruler',
        price: '$22',
        description: 'A weighted, solid aluminum triangular scale with precise laser-etched metric measurements.',
        link: '#',
      },
      {
        id: 'd_c3',
        name: 'Linen-Bound Hardcover Weekly Planner',
        price: '$34',
        description: 'Undated minimalist format featuring high-density 120gsm cream paper for pristine writing.',
        link: '#',
      },
      {
        id: 'd_c4',
        name: 'Magnetic Wooden Cable Blocks',
        price: '$28',
        description: 'Pair of hand-finished walnut blocks that snap together to keep cables from falling off.',
        link: '#',
      },
    ],
  },
  {
    id: 'wellness-sanctuary',
    title: 'The Wellness Sanctuary',
    picksCount: 14,
    badgeBg: 'bg-[#e07a5f]',
    badgeText: 'text-white',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop',
    description: 'Calming rituals, therapeutic aromatherapy, and tactile comforts for deep restoration.',
    category: 'occasions',
    tags: ['Wellness', 'Self-Care', 'Restoration'],
    items: [
      {
        id: 'w_s1',
        name: 'Acoustic Sound Therapy Bowl',
        price: '$52',
        description: 'Hand-hammered brass singing bowl crafted in Nepal with mahogany striker and velvet cushion.',
        link: '#',
      },
      {
        id: 'w_s2',
        name: 'Organic Lavender & Eucalyptus Mist',
        price: '$24',
        description: 'Small-batch botanical pillow and room spray steam-distilled from pure organic French lavender.',
        link: '#',
      },
      {
        id: 'w_s3',
        name: 'Weighted Velvet Eyebag & Warm Compress',
        price: '$32',
        description: 'Filled with organic flaxseed and dried lavender buds to relieve eye tension gently.',
        link: '#',
      },
      {
        id: 'w_s4',
        name: 'Handcrafted Sandalwood Massage Roller',
        price: '$28',
        description: 'Smooth, ergonomic green sandalwood roller that emits a subtle natural wood aroma.',
        link: '#',
      },
    ],
  },
  {
    id: 'plant-parent',
    title: 'The Urban Botanist',
    picksCount: 12,
    badgeBg: 'bg-[#81b29a]',
    badgeText: 'text-white',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=600&auto=format&fit=crop',
    description: 'Terracotta vessels, precision brass misters, and botanical care essentials.',
    category: 'recipients',
    tags: ['Botanical', 'Home', 'Green'],
    items: [
      {
        id: 'p_p1',
        name: 'Brushed Solid Brass Water Mister',
        price: '$36',
        description: 'Delivers a fine vintage cloud of mist ideal for delicate ferns, orchids, and tropical houseplants.',
        link: '#',
      },
      {
        id: 'p_p2',
        name: 'Raw Terracotta Modular Planter',
        price: '$42',
        description: 'Hand-thrown porous clay pot with built-in drainage tray to keep plant roots healthy.',
        link: '#',
      },
      {
        id: 'p_p3',
        name: 'Handcrafted Japanese Pruning Shears',
        price: '$48',
        description: 'High-carbon steel blades with woven rattan handles for precision trimming and propagation.',
        link: '#',
      },
    ],
  },
  {
    id: 'analog-vault',
    title: 'The Analog & Vinyl Vault',
    picksCount: 16,
    badgeBg: 'bg-[#d4a373]',
    badgeText: 'text-white',
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=600&auto=format&fit=crop',
    description: 'Hi-fi care kits, wooden record crates, and tactile listening station treats.',
    category: 'recent',
    tags: ['Music', 'Vinyl', 'Nostalgic'],
    items: [
      {
        id: 'a_v1',
        name: 'Goat Hair Anti-Static Vinyl Brush',
        price: '$26',
        description: 'Ultra-soft natural goat hair brush paired with walnut handle to remove dust silently.',
        link: '#',
      },
      {
        id: 'a_v2',
        name: 'Solid Oak Vinyl Display Ledge',
        price: '$34',
        description: 'Minimalist wall-mounted shelf designed to spotlight your currently playing album art.',
        link: '#',
      },
      {
        id: 'a_v3',
        name: 'Hand-Stitched Leather Record Weight Clamp',
        price: '$45',
        description: 'Reduces turntable vibration and improves acoustic clarity for vintage pressings.',
        link: '#',
      },
    ],
  },
  {
    id: 'celestial-observatory',
    title: 'The Celestial Observatory',
    picksCount: 13,
    badgeBg: 'bg-[#2b2d42]',
    badgeText: 'text-white',
    image: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=600&auto=format&fit=crop',
    description: 'Brass astrolabes, night-sky star maps, and deep space wonder objects.',
    category: 'occasions',
    tags: ['Astronomy', 'Celestial', 'Stargazing'],
    items: [
      {
        id: 'c_o1',
        name: 'Brass Desktop Armillary Sphere & Sundial',
        price: '$68',
        description: 'Solid brass celestial globe with engraved zodiac rings and antique patina finish.',
        link: '#',
      },
      {
        id: 'c_o2',
        name: 'Custom Glow-In-The-Dark Constellation Map',
        price: '$38',
        description: 'Personalized star map rendered on heavy midnight blue velvet paper with metallic gold foil.',
        link: '#',
      },
      {
        id: 'c_o3',
        name: 'Meteorite Fragment Pendant & Certificate',
        price: '$85',
        description: 'Real nickel-iron Campo del Cielo meteorite slice mounted in sterling silver.',
        link: '#',
      },
    ],
  },
];
