import type { Product } from './types';

export const PRODUCT_CATALOG: Product[] = [
  {
    id: 'p1',
    name: 'Artisanal Pasta & Sauce Masterclass (E-Voucher)',
    price: '$65',
    priceEstimate: '$65',
    description: 'An interactive, live streaming or instant-access cooking class voucher with a celebrity chef for two.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'EXPERIENCE',
    productType: 'Other',
    relationships: ['boyfriend', 'girlfriend', 'close_friend', 'sibling', 'coworker'],
    occasions: ['birthday', 'anniversary', 'just_because', 'milestone', 'holiday'],
    personalities: ['homebody', 'aesthete', 'dreamer', 'planner'],
    giftLanguage: ['quality_time', 'surprises'],
    priceTier: 'mid',
    relationshipStage: ['a_few_months', 'long_term', 'known_forever', 'close', 'new_clicking'],
    deliveryType: 'instant',
    active: true,
  },
  {
    id: 'p2',
    name: 'Handcrafted Custom Memory Photo Book Kit',
    price: '$42',
    priceEstimate: '$42',
    description: 'Embossed linen scrapbook kit with archival printing voucher, corner stickers, and gold ink pen.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'SENTIMENTAL',
    productType: 'Other',
    relationships: ['mom', 'dad', 'grandparent', 'boyfriend', 'girlfriend', 'close_friend', 'sibling'],
    occasions: ['birthday', 'anniversary', 'just_because', 'goodbye', 'missing_them', 'hard_times'],
    personalities: ['dreamer', 'aesthete', 'planner'],
    giftLanguage: ['words', 'physical_gift'],
    priceTier: 'mid',
    relationshipStage: ['long_term', 'close', 'known_forever', 'reconnecting', 'long_distance'],
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p3',
    name: 'Hand-Forged 67-Layer Damascus Paring Knife',
    price: '$120',
    priceEstimate: '$120',
    description: 'Ultra-sharp Japanese VG-10 steel core with ergonomically balanced olive wood handle in a velvet gift box.',
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'PRACTICAL',
    productType: 'Other',
    relationships: ['dad', 'boyfriend', 'girlfriend', 'sibling', 'coworker', 'close_friend'],
    occasions: ['birthday', 'milestone', 'holiday', 'just_because'],
    personalities: ['practical', 'aesthete', 'planner'],
    giftLanguage: ['physical_gift', 'acts_of_service'],
    priceTier: 'generous',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p4',
    name: 'Mindfulness & Guided Wellness App E-Membership (1 Year)',
    price: '$28',
    priceEstimate: '$28',
    description: 'Instant digital gift code giving unlimited access to curated audio meditations, sleep stories, and soundscapes.',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'WELLNESS',
    productType: 'Other',
    relationships: ['mom', 'close_friend', 'coworker', 'sibling', 'other', 'grandparent'],
    occasions: ['just_because', 'hard_times', 'birthday', 'holiday'],
    personalities: ['homebody', 'dreamer', 'planner'],
    giftLanguage: ['words', 'acts_of_service', 'surprises'],
    priceTier: 'modest',
    relationshipStage: ['just_started', 'new_clicking', 'complicated', 'love_not_close', 'close'],
    deliveryType: 'instant',
    active: true,
  },
  {
    id: 'p5',
    name: 'Live Theater & Concert E-Gift Pass',
    price: '$95',
    priceEstimate: '$95',
    description: 'Instant ticket pass for local intimate acoustic gigs, comedy clubs, or independent theater plays.',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'EXPERIENCE',
    productType: 'Other',
    relationships: ['boyfriend', 'girlfriend', 'close_friend', 'school_friend', 'sibling'],
    occasions: ['birthday', 'anniversary', 'milestone', 'just_because', 'holiday'],
    personalities: ['adventurer', 'jokester', 'aesthete'],
    giftLanguage: ['quality_time', 'surprises'],
    priceTier: 'generous',
    deliveryType: 'instant',
    active: true,
  },
  {
    id: 'p6',
    name: 'Solid Brass Pocket Pen & Key Organizer Set',
    price: '$32',
    priceEstimate: '$32',
    description: 'Weighted solid brass pocket tool and silent key organizer that builds a gorgeous unique patina over time.',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'PRACTICAL',
    productType: 'Other',
    relationships: ['dad', 'boyfriend', 'coworker', 'sibling', 'close_friend', 'school_friend'],
    occasions: ['birthday', 'just_because', 'milestone', 'holiday'],
    personalities: ['practical', 'planner', 'adventurer'],
    giftLanguage: ['acts_of_service', 'physical_gift'],
    priceTier: 'mid',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p7',
    name: 'Old Library Wood & Vanilla Soy Amber Candle',
    price: '$26',
    priceEstimate: '$26',
    description: 'Hand-poured soy candle with notes of mahogany wood, worn leather covers, and warm amber vanilla.',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'COZY',
    productType: 'Candles',
    relationships: ['mom', 'close_friend', 'coworker', 'sibling'],
    occasions: ['just_because', 'holiday', 'birthday'],
    personalities: ['homebody', 'dreamer'],
    giftLanguage: ['physical_gift'],
    priceTier: 'modest',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p8',
    name: 'Japanese Hinoki Coffee Spoon & Single-Origin Beans',
    price: '$38',
    priceEstimate: '$38',
    description: 'Handcrafted cypress coffee scoop paired with 12oz micro-batch roasted beans from Ethiopia.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'ARTISANAL',
    productType: 'Other',
    relationships: ['boyfriend', 'girlfriend', 'close_friend', 'coworker', 'dad', 'sibling'],
    occasions: ['birthday', 'just_because', 'holiday', 'apology'],
    personalities: ['aesthete', 'planner', 'homebody'],
    giftLanguage: ['acts_of_service', 'physical_gift'],
    priceTier: 'mid',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p9',
    name: 'Irreverent Tabletop Card Game & Secret Snack Box',
    price: '$29',
    priceEstimate: '$29',
    description: 'Hilarious fast-paced party game packed with gourmet Japanese sweet and savory snack treats.',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'PLAYFUL',
    productType: 'Other',
    relationships: ['school_friend', 'close_friend', 'sibling', 'boyfriend', 'coworker'],
    occasions: ['birthday', 'just_because', 'apology', 'holiday'],
    personalities: ['jokester', 'adventurer'],
    giftLanguage: ['surprises', 'physical_gift'],
    priceTier: 'modest',
    relationshipStage: ['new_clicking', 'known_forever', 'reconnecting', 'a_few_months'],
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p10',
    name: 'Custom Coordinates Stamped Brass Keychain',
    price: '$22',
    priceEstimate: '$22',
    description: 'Solid brass bar stamped with the exact longitude and latitude coordinates of where you first met.',
    image: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'SENTIMENTAL',
    productType: 'Other',
    relationships: ['boyfriend', 'girlfriend', 'school_friend', 'close_friend'],
    occasions: ['anniversary', 'missing_them', 'goodbye', 'just_because'],
    personalities: ['dreamer', 'planner'],
    giftLanguage: ['words', 'physical_gift'],
    priceTier: 'modest',
    relationshipStage: ['long_distance', 'long_term', 'reconnecting', 'just_started'],
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p11',
    name: 'Nostalgic Sweets & Comfort Cocoa Gift Box',
    price: '$25',
    priceEstimate: '$25',
    description: 'Curated box of small-batch drinking chocolate, toasted marshmallows, and retro biscuit tins.',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'NOSTALGIC',
    productType: 'Other',
    relationships: ['school_friend', 'close_friend', 'coworker', 'sibling', 'grandparent', 'mom'],
    occasions: ['just_because', 'birthday', 'hard_times', 'holiday'],
    personalities: ['homebody', 'jokester', 'practical'],
    giftLanguage: ['surprises', 'acts_of_service'],
    priceTier: 'modest',
    relationshipStage: ['reconnecting', 'new_clicking', 'love_not_close', 'complicated'],
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p12',
    name: 'Ultralight Tyvek Compression Packing Cubes',
    price: '$30',
    priceEstimate: '$30',
    description: 'Featherlight water-resistant packing cubes that compress clothing down to 50% volume for easy travel.',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'GEAR',
    productType: 'Storage',
    relationships: ['close_friend', 'sibling', 'boyfriend', 'girlfriend', 'coworker', 'school_friend'],
    occasions: ['milestone', 'birthday', 'just_because', 'goodbye'],
    personalities: ['adventurer', 'practical', 'planner'],
    giftLanguage: ['acts_of_service', 'physical_gift'],
    priceTier: 'modest',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p13',
    name: 'Custom Handwritten Letter & Pressed Botanical Frame',
    price: '$24',
    priceEstimate: '$24',
    description: 'Elegant brass glass frame displaying pressed wildflowers and your personal note transcribed in calligraphic print.',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'SENTIMENTAL',
    productType: 'Other',
    relationships: ['mom', 'grandparent', 'girlfriend', 'boyfriend', 'close_friend'],
    occasions: ['just_because', 'birthday', 'anniversary', 'missing_them', 'hard_times', 'apology'],
    personalities: ['dreamer', 'aesthete'],
    giftLanguage: ['words'],
    priceTier: 'modest',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p14',
    name: 'Pure Mulberry Silk Pillowcase & Sleep Mask Set',
    price: '$85',
    priceEstimate: '$85',
    description: '100% 22-momme Grade 6A natural mulberry silk that protects delicate skin and hair during rest.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'LUXURY',
    productType: 'Clothes',
    relationships: ['mom', 'girlfriend', 'close_friend', 'grandparent', 'sibling'],
    occasions: ['birthday', 'anniversary', 'holiday', 'hard_times', 'just_because'],
    personalities: ['aesthete', 'homebody'],
    giftLanguage: ['physical_gift', 'acts_of_service'],
    priceTier: 'generous',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p15',
    name: 'Luxury Weekend Getaway E-Gift Fund',
    price: '$200',
    priceEstimate: '$200',
    description: 'Instant e-voucher redeemable for boutique cabin stays, wellness retreats, or scenic vineyard tours.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'EXPERIENCE',
    productType: 'Other',
    relationships: ['boyfriend', 'girlfriend', 'mom', 'dad', 'sibling'],
    excludeRelationships: ['coworker'],
    occasions: ['anniversary', 'milestone', 'birthday'],
    personalities: ['adventurer', 'dreamer', 'aesthete'],
    giftLanguage: ['quality_time', 'surprises'],
    priceTier: 'no_limit',
    relationshipStage: ['long_term', 'close'],
    deliveryType: 'instant',
    active: true,
  },
  {
    id: 'p16',
    name: 'Custom Ceramic Speckled Artisan Mug',
    price: '$28',
    priceEstimate: '$28',
    description: 'Hand-thrown stoneware coffee mug with a cozy tactile grip and natural oat-colored glaze.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop',
    link: '#',
    categoryTag: 'COZY',
    productType: 'Mugs',
    relationships: ['mom', 'coworker', 'close_friend', 'sibling'],
    occasions: ['just_because', 'holiday'],
    personalities: ['homebody', 'aesthete'],
    giftLanguage: ['physical_gift'],
    priceTier: 'modest',
    deliveryType: 'shippable',
    active: true,
  },
  {
    id: 'p17',
    name: 'Draft Concept Item (Inactive)',
    price: '$15',
    priceEstimate: '$15',
    description: 'Unpublished sample item for testing active filter.',
    image: '',
    link: '#',
    categoryTag: 'DRAFT',
    productType: 'Other',
    relationships: ['boyfriend'],
    occasions: ['birthday'],
    personalities: ['planner'],
    giftLanguage: ['words'],
    priceTier: 'modest',
    deliveryType: 'shippable',
    active: false,
  },
];
